### ISSUE TITLE
Cannot pip install on Windows

### ISSUE THREAD

**Issue by WarleyLopes** [andyjmc/file-upload-ipywidget#4]
Hey @andyjmc, I hope you're doing great!

Unfortunately, I ran into this issue while trying to install this package on Windows, I did some researches and couldn't see anything else I could do by my part to get this installed and it seems there are other packages that got this installing issue on Windows as well, so I'm submitting this in hope that you can help in some sort, thanks a lot in advance!

After running ```pip install git+https://github.com/andyjmc/file-upload-ipywidget```, I get the following error:
```
    Running setup.py install for uploader-widget ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\diley\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\diley\\A
ppData\\Local\\Temp\\pip-install-wda5mrhp\\uploader-widget\\setup.py'"'"'; __file__='"'"'C:\\Users\\diley\\AppData\\Local\\Temp\\pip-install-wda5mrhp\\uploader-wid
get\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '
"'"'exec'"'"'))' install --record 'C:\Users\diley\AppData\Local\Temp\pip-record-_fo3blgu\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\diley\AppData\Local\Temp\pip-install-wda5mrhp\uploader-widget\
    Complete output (66 lines):
    setup.py entered
    $PATH=C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1
.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\WinMerge;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLIS
R;C:\Program Files\Git\cmd;C:\Program Files\PuTTY\;C:\Users\diley\AppData\Local\Programs\Python\Python37-32\Scripts\;C:\Users\diley\AppData\Local\Programs\Python\P
ython37-32\;C:\Users\diley\AppData\Local\Microsoft\WindowsApps;C:\Users\diley\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\diley\AppData\Local\Microsoft\G
itHubDesktop\bin;C:\Users\diley\AppData\Local\Microsoft\WindowsApps;C:\Users\diley\bin;;c:\users\diley\appdata\local\programs\python\python37-32\lib\site-packages\
pywin32_system32
    running install
    running build
    running build_py
    running jsdeps
    `npm` unavailable.  If you're running this command using sudo, make sure `npm` is available to sudo
    creating build
    creating build\lib
    creating build\lib\uploader_widget
    copying uploader_widget\uploader.py -> build\lib\uploader_widget
    copying uploader_widget\_version.py -> build\lib\uploader_widget
    copying uploader_widget\__init__.py -> build\lib\uploader_widget
    running egg_info
    creating uploader_widget.egg-info
    writing uploader_widget.egg-info\PKG-INFO
    writing dependency_links to uploader_widget.egg-info\dependency_links.txt
    writing requirements to uploader_widget.egg-info\requires.txt
    writing top-level names to uploader_widget.egg-info\top_level.txt
    writing manifest file 'uploader_widget.egg-info\SOURCES.txt'
    reading manifest file 'uploader_widget.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'uploader_widget.egg-info\SOURCES.txt'
    creating build\lib\uploader_widget\static
    copying uploader_widget\static\extension.js -> build\lib\uploader_widget\static
    copying uploader_widget\static\index.js -> build\lib\uploader_widget\static
    copying uploader_widget\static\index.js.map -> build\lib\uploader_widget\static
    running install_lib
    copying build\lib\uploader_widget\static\extension.js -> c:\users\diley\appdata\local\programs\python\python37-32\Lib\site-packages\uploader_widget\static
    copying build\lib\uploader_widget\static\index.js -> c:\users\diley\appdata\local\programs\python\python37-32\Lib\site-packages\uploader_widget\static
    copying build\lib\uploader_widget\static\index.js.map -> c:\users\diley\appdata\local\programs\python\python37-32\Lib\site-packages\uploader_widget\static
    copying build\lib\uploader_widget\uploader.py -> c:\users\diley\appdata\local\programs\python\python37-32\Lib\site-packages\uploader_widget
    copying build\lib\uploader_widget\_version.py -> c:\users\diley\appdata\local\programs\python\python37-32\Lib\site-packages\uploader_widget
    copying build\lib\uploader_widget\__init__.py -> c:\users\diley\appdata\local\programs\python\python37-32\Lib\site-packages\uploader_widget
    byte-compiling c:\users\diley\appdata\local\programs\python\python37-32\Lib\site-packages\uploader_widget\uploader.py to uploader.cpython-37.pyc
    byte-compiling c:\users\diley\appdata\local\programs\python\python37-32\Lib\site-packages\uploader_widget\_version.py to _version.cpython-37.pyc
    byte-compiling c:\users\diley\appdata\local\programs\python\python37-32\Lib\site-packages\uploader_widget\__init__.py to __init__.cpython-37.pyc
    running install_data
    copying uploader_widget\static\extension.js -> c:\users\diley\appdata\local\programs\python\python37-32\share\jupyter\nbextensions\uploader_widget
    copying uploader_widget\static\index.js -> c:\users\diley\appdata\local\programs\python\python37-32\share\jupyter\nbextensions\uploader_widget
    copying uploader_widget\static\index.js.map -> c:\users\diley\appdata\local\programs\python\python37-32\share\jupyter\nbextensions\uploader_widget
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\diley\AppData\Local\Temp\pip-install-wda5mrhp\uploader-widget\setup.py", line 176, in <module>
        setup(**setup_args)
      File "c:\users\diley\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\diley\appdata\local\programs\python\python37-32\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\diley\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\diley\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\diley\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\diley\appdata\local\programs\python\python37-32\lib\distutils\command\install.py", line 557, in run
        self.run_command(cmd_name)
      File "c:\users\diley\appdata\local\programs\python\python37-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\diley\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\diley\appdata\local\programs\python\python37-32\lib\distutils\command\install_data.py", line 56, in run
        dir = convert_path(f[0])
      File "c:\users\diley\appdata\local\programs\python\python37-32\lib\distutils\util.py", line 112, in convert_path
        raise ValueError("path '%s' cannot end with '/'" % pathname)
    ValueError: path 'etc/jupyter/nbconfig/notebook.d/' cannot end with '/'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\diley\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.a
rgv[0] = '"'"'C:\\Users\\diley\\AppData\\Local\\Temp\\pip-install-wda5mrhp\\uploader-widget\\setup.py'"'"'; __file__='"'"'C:\\Users\\diley\\AppData\\Local\\Temp\\p
ip-install-wda5mrhp\\uploader-widget\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close
();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\diley\AppData\Local\Temp\pip-record-_fo3blgu\install-record.txt' --single-version-exte
rnally-managed --compile Check the logs for full command output.
```

Similar to installing other packages on Windows:
https://github.com/maartenbreddels/ipymaterialui/issues/5
https://github.com/QuantStack/ipysheet/issues/9

**Comment by WarleyLopes** [comment]
I cloned, removed the slash and ended up adding ```\\``` at the final instead on the initial path ``` 'etc/jupyter/nbconfig/notebook.d/'``` path, built it and I was able to continue with the development setup locally described on readme, although, I'm not sure if this would impact the installation on other environments

**Comment by andyjmc** [comment]
@WarleyLopes did you manage to sort this issue?

**Comment by WarleyLopes** [comment]
Hey @andyjmc! Thanks for the reply, I cloned, changed the slashes and installed it locally to sort out the issue temporarily and be able to finish with the installation.

Maybe using ```os.sep``` to replace the slashes may be a proper fix to work for all operational systems.
